name: Frontend CI/CD

on:
  push:
    branches: [main]

env:
  ACR_NAME: chalsacrname
  ACR_LOGIN_SERVER: chalsacrname.azurecr.io
  AKS_RESOURCE_GROUP: myResourceGroup
  AKS_CLUSTER_NAME: chalsAKSCluster
  IMAGE_NAME: kubernets-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      run: az acr login --name $ACR_NAME

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Get Backend External IP
      id: get-backend-ip
      run: |
        IP=$(kubectl get svc backend -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "VITE_API_BASE_URL=http://$IP:3001" >> $GITHUB_ENV
        echo "Backend IP is: $IP"

    - name: Build and Push Frontend Image
      run: |
        docker build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL -t $ACR_LOGIN_SERVER/$IMAGE_NAME:v${{ github.run_number }} .
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:v${{ github.run_number }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/frontend $IMAGE_NAME=$ACR_LOGIN_SERVER/$IMAGE_NAME:v${{ github.run_number }}
